# Exception

```cs
namespace ExceptionExample
{
    internal class Program
    {
        static void Main(string[] args)
        {
            int i;
            i = int.Parse("10");
            Console.WriteLine($"i = {i}");
            int j;
            j = int.Parse("Ten");
            Console.WriteLine($"j = {j}");
        }
    }
}
```


```cs
namespace ExceptionExample
{
    internal class Program
    {
        static void Main(string[] args)
        {
            int i;
            i = int.Parse("10");
            Console.WriteLine($"i = {i}");

            int j;
            try
            {
                j = int.Parse("Ten");
                Console.WriteLine($"j = {j}");
            }
            catch
            {
                Console.WriteLine("Invalid number.");
            }
        }
    }
}
```



## Catching exception


```cs
namespace ExceptionExample
{
    internal class Program
    {
        static void Main(string[] args)
        {
            int i;
            i = int.Parse("10");
            Console.WriteLine($"i = {i}");

            int j;
            try
            {
                j = int.Parse("Ten");
                Console.WriteLine($"j = {j}");
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
                Console.WriteLine(e.StackTrace);
            }
        }
    }
}
```


## Try-catch-finally

``` cs
namespace ExceptionExample
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("--- input string = \"10\" ---");
            int i;
            try
            {
                i = int.Parse("10");
                Console.WriteLine($"i = {i}");
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                Console.WriteLine(e.StackTrace);
            }
            finally
            {
                Console.WriteLine("Normal routine operation");
            }

            Console.WriteLine("--- input string = \"Ten\" ---");
            int j;
            try
            {
                j = int.Parse("Ten");
                Console.WriteLine($"j = {j}");
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
                Console.WriteLine(e.StackTrace);
            }
            finally 
            {
                Console.WriteLine("Normal routine operation");
            }
            Console.WriteLine("--- End Program ---");
        }
    }
}
```




