# 15.2 Exception

## 15.2.1 Throw exception

รันโปรแกรมต่อไปนี้ แล้วบันทึกผลการรัน

```cs
namespace ExceptionExample
{
    class CustomException : Exception
    {
        public CustomException(string message)
        {
        }
    }
    internal class Program
    {
        static void Main(string[] args)
        {
            try
            {
                throw new CustomException("Custom exception in TestThrow()");
            }
            catch (CustomException ex)
            {
                Console.WriteLine(ex);
            }
        }
    }
}
```
![ภาพ](https://github.com/kammam19/Week-15/assets/112167732/4bb1472f-2de1-43e6-b557-c55cbd8842f4)



## 15.2.2 Throw exception

รันโปรแกรมต่อไปนี้ แล้วบันทึกผลการรัน

```cs
using System;
using System.IO;

namespace Exceptions
{
    public class CatchOrder
    {
        public static void Main()
        {
            try
            {
                using (var sw = new StreamWriter("./test.txt"))
                {
                    sw.WriteLine("Hello");
                }
                using (var sr = new StreamReader("./test.txt"))
                {
                    Console.WriteLine(sr.ReadLine());
                }
                using (var sr = new StreamReader("./test1.txt"))
                {
                    Console.WriteLine(sr.ReadLine());
                }
            }
            // Put the more specific exceptions first.
            catch (DirectoryNotFoundException ex)
            {
                Console.WriteLine(ex);
            }
            catch (FileNotFoundException ex)
            {
                Console.WriteLine(ex);
            }
            // Put the least specific exception last.
            catch (IOException ex)
            {
                Console.WriteLine(ex);
            }
            Console.WriteLine("Done");
        }
    }
}
```
![ภาพ](https://github.com/kammam19/Week-15/assets/112167732/c3d21413-cb7e-4792-a9b4-795b9dc70865)

